# WEEK 12 - 4 PILLARS OF OOP (OBJECT-ORIENTED PROGRAMMING)
# - ENCAPSULATION: PROTECTING DATA BY RESTRICTING ACCESS TO CERTAIN COMPONENTS
# - ABSTRACTION: HIDING COMPLEXITY BY PROVIDING A SIMPLIFIED INTERFACE
# - INHERITANCE: THIS HELPS TO REUSE CODE AND CREATE A HIERARCHY OF CLASSES
# - POLYMORPHISM: THIS HELPS TO USE A SINGLE INTERFACE FOR DIFFERENT DATA TYPES

from abc import ABC, abstractmethod # IMPORT THE ABSTRACT BASE CLASS MODULE TO CREATE ABSTRACT CLASSES

import math # IMPORT MATH MODULE TO USE PI CONSTANT AND OTHER MATH FUNCTIONS


"""MAIN ABSTRACT CLASS (SUPERCLASS) - SHAPE"""
class Shape(ABC): # DEFINE THE ABSTRACT BASE CLASS SHAPE - ALL GEOMETRIC SHAPES WILL INHERIT FROM THIS
    
    @abstractmethod # DECORATOR THAT MARKS THIS METHOD AS ABSTRACT (MUST BE IMPLEMENTED BY CHILD CLASSES)
    def calculate_perimeter(self): # METHOD TO CALCULATE AND RETURN THE PERIMETER OF THE SHAPE
        """Calculate and return the perimeter of the shape"""
        pass # ABSTRACT METHODS HAVE NO IMPLEMENTATION IN THE BASE CLASS (PASS IS USED)
    

    @abstractmethod # DECORATOR THAT MARKS THIS METHOD AS ABSTRACT (MUST BE IMPLEMENTED BY CHILD CLASSES)
    def calculate_area(self): # METHOD TO CALCULATE AND RETURN THE AREA OF THE SHAPE
        """Calculate and return the area of the shape"""
        pass # NO IMPLEMENTATION HERE - CHILD CLASSES MUST PROVIDE THEIR OWN VERSION
    
    def display_info(self): # THIS IS A CONCRETE (NORMAL) METHOD THAT ALL SHAPES CAN USE OR OVERRIDE
        return (f"Area: {self.calculate_area():.2f} | " # RETURNS A FORMATTED STRING WITH BOTH AREA AND PERIMETER VALUES
                f"Perimeter: {self.calculate_perimeter():.2f}")


""" CHILD CLASS (SUBCLASS) - CIRCLE """
class Circle(Shape): # CIRCLE CLASS THAT INHERITS FROM SHAPE ABSTRACT CLASS 
    def __init__(self, radius):  # CONSTRUCTOR METHOD - INITIALIZES A NEW CIRCLE OBJECT AND TAKES RADIUS AS PARAMETER
        if radius <= 0: # CHECKS IF RADIUS IS VALID (MUST BE POSITIVE)
            raise ValueError("Radius must be greater than zero") # RAISE ERROR IF RADIUS IS ZERO OR NEGATIVE
        self.radius = radius # STORE THE RADIUS VALUE AS INSTANCE ATTRIBUTE OF THE CIRCLE OBJECT
    

    def calculate_perimeter(self): # IMPLEMENTATION OF ABSTRACT METHOD - CALCULATES CIRCUMFERENCE
        return 2 * math.pi * self.radius # CIRCUMFERENCE FORMULA: 2 × π × radius
    
    
    def calculate_area(self): # IMPLEMENTATION OF ABSTRACT METHOD - CALCULATES AREA
        return math.pi * self.radius ** 2 # AREA FORMULA: π × radius²


""" CHILD CLASS (SUBCLASS) - SQUARE """
class Square(Shape): # SQUARE CLASS THAT INHERITS FROM SHAPE
    def __init__(self, side): # CONSTRUCTOR - TAKES ONE PARAMETER (SIDE LENGTH)
        if side <= 0: # VALIDATION: SIDE MUST BE POSITIVE
            raise ValueError("Side must be greater than zero") # RAISE ERROR IF INVALID
        self.side = side # STORE SIDE LENGTH
    
    # PERIMETER OF SQUARE = 4 × SIDE
    def calculate_perimeter(self): #THIS METHOD IS INHERITED FROM SHAPE AND CALCULATES PERIMETER OF SQUARE
        return 4 * self.side
    
    # AREA OF SQUARE = SIDE × SIDE
    def calculate_area(self): # THIS METHOD IS INHERITED FROM SHAPE AND CALCULATES AREA OF SQUARE
        return self.side ** 2


""" CHILD CLASS (SUBCLASS) - RECTANGLE """
class Rectangle(Shape): # RECTANGLE CLASS THAT INHERITS FROM SHAPE
    def __init__(self, length, width): # CONSTRUCTOR TAKES TWO PARAMETERS: LENGTH AND WIDTH
        if length <= 0 or width <= 0: # VALIDATION: BOTH DIMENSIONS MUST BE POSITIVE
            raise ValueError("Both length and width must be greater than zero") # RAISE ERROR IF INVALID
        # ONCE THE VALIDATION PASSES AND THE DIMENSIONS ARE CALCULATED, WE PROCEED TO STORE BOTH VALUES, LENGTH AND WIDTH, AS INSTANCE ATTRIBUTES OF THE RECTANGLE OBJECT.
        self.length = length
        self.width = width
    
    # PERIMETER FORMULA: 2 × (LENGTH + WIDTH)
    def calculate_perimeter(self): # THIS METHOD IS INHERITED FROM SHAPE AND CALCULATES PERIMETER OF RECTANGLE
        return 2 * (self.length + self.width) #THIS IS THE FORMULA TO CALCULATE THE PERIMETER OF A RECTANGLE.
    #THIS FORMULA TAKES INTO ACCOUNT BOTH THE LENGTH AND WIDTH OF THE RECTANGLE, MULTIPLYING THEIR SUM BY 2 TO GET THE TOTAL PERIMETER.
    # THIS ENSURES THAT ALL SIDES (FOUR SIDES IN TOTAL) ARE ACCOUNTED FOR IN THE PERIMETER CALCULATION.
    
    # AREA FORMULA: LENGTH × WIDTH
    def calculate_area(self): # THIS METHOD IS INHERITED FROM SHAPE AND CALCULATES AREA OF RECTANGLE
        return self.length * self.width #THIS IS THE FORMULA TO CALCULATE THE AREA OF A RECTANGLE.
    # THIS FORMULA MULTIPLIES THE LENGTH BY THE WIDTH TO GET THE TOTAL AREA COVERED BY THE RECTANGLE.


if __name__ == "__main__": # THIS BLOCK RUNS ONLY WHEN THIS FILE IS EXECUTED DIRECTLY (NOT WHEN IMPORTED)
    try:
        # THIS IS WHERE THE MAGIC HAPPENS, WE ARE CREATING THE SHAPES OUT OF THE CLASSES DEFINED ABOVE
        # FOLLOWING THE ANALOGY OF A SHAPE FACTORY, WE INSTANTIATE DIFFERENT SHAPES WITH SPECIFIC DIMENSIONS
        circle = Circle(5)      # CIRCLE WITH RADIUS 5
        square = Square(4)      # SQUARE WITH SIDE 4
        rectangle = Rectangle(6, 3)  # RECTANGLE 6×3
        
        
        print("Circle (radius = 5):") #HERE WE ARE PRINTING THE TYPE OF SHAPE AND ITS DIMENSIONS
        print(circle.display_info()) #HERE WE ARE CALLING THE DISPLAY METHOD FOR EACH SHAPE TO SHOW THEIR AREA AND PERIMETER
        print()  # THIS LINE IS FOR AESTHETIC PURPOSES, TO ADD A BLANK LINE BETWEEN OUTPUTS FOR BETTER READABILITY.
        
        print("Square (side = 4):")
        print(square.display_info())
        print() # THIS LINE IS FOR AESTHETIC PURPOSES, TO ADD A BLANK LINE BETWEEN OUTPUTS FOR BETTER READABILITY.
        
        print("Rectangle (length = 6, width = 3):")
        print(rectangle.display_info())
        
    # CATCH VALUE ERRORS (INVALID DIMENSIONS) AND SHOW FRIENDLY MESSAGE
    except ValueError as e:
        print(f"Error: {e}")
