#THIS FUNCTION DECORATOR ENSURES THAT ALL ARGUMENTS PASSED TO THE DECORATED FUNCTION ARE NUMBERS (INT OR FLOAT)
# IF ANY ARGUMENT IS NOT A NUMBER → IT RAISES A TYPEERROR WITH A CLEAR MESSAGE INDICATING WHICH VALUE FAILED THE CHECK
# THIS IS USEFUL TO PREVENT ERRORS IN FUNCTIONS THAT EXPECT NUMERIC INPUTS, AND TO PROVIDE FEEDBACK IMMEDIATELY IF THE WRONG TYPE OF DATA IS PASSED
# THE DECORATOR USES A WRAPPER FUNCTION TO INTERCEPT THE CALL TO THE ORIGINAL FUNCTION, CHECK THE ARGUMENTS, AND THEN EITHER RAISE AN ERROR OR CALL THE ORIGINAL FUNCTION IF ALL CHECKS PASS
# IN THE REAL WORLD, THIS KIND OF DECORATOR CAN BE VERY USEFUL IN DATA VALIDATION SCENARIOS, WHERE YOU WANT TO ENSURE THAT...
# YOUR FUNCTIONS RECEIVE THE CORRECT TYPE OF INPUT BEFORE PROCEEDING WITH THE LOGIC

def only_numbers(func): #THE VALUE func REPRESENTS THE FUNCTION THAT WE WANT TO DECORATE
    def wrapper(*args): #THE wrapper FUNCTION WILL REPLACE THE ORIGINAL FUNCTION, AND *args ALLOWS US TO ACCEPT ANY NUMBER OF POSITIONAL ARGUMENTS
        for arg in args: # LOOP THROUGH EVERY ARGUMENT RECEIVED BY THE FUNCTION
            # ISINSTANCE CHECKS IF THE VALUE BELONGS TO ONE OF THE ALLOWED TYPES
            # (int, float) → WE PASS A TUPLE SO IT CHECKS AGAINST MULTIPLE TYPES AT ONCE
            if not isinstance(arg, (int, float)):
                # RAISE TYPEERROR WITH A VERY DESCRIPTIVE MESSAGE
                # WE INCLUDE THE ACTUAL WRONG VALUE SO THE USER KNOWS EXACTLY WHAT FAILED
                raise TypeError(f"All parameters must be numbers! Found: {arg} (type: {type(arg).__name__})")
        
        # IF WE REACH THIS POINT → ALL ARGUMENTS ARE int OR float, THEREFORE, IT IS SAFE TO CALL THE ORIGINAL FUNCTION
        return func(*args) # CALL THE ORIGINAL FUNCTION WITH THE SAME ARGUMENTS
    
    return wrapper # RETURN THE WRAPPER FUNCTION TO COMPLETE THE DECORATOR
"""THE DIFFERENCE BETWEEN THE FIRST RETURN AND THE SECOND ONE IS THAT THE FIRST ONE RETURNS 
THE RESULT OF CALLING THE ORIGINAL FUNCTION (func(*args)), WHILE THE SECOND ONE RETURNS 
THE WRAPPER FUNCTION ENCAPSULATED WITHIN THE DECORATOR (only_numbers)"""


# ────────────────────────────────────────────────
#                  EXAMPLE USAGE
# ────────────────────────────────────────────────

@only_numbers # APPLY THE DECORATOR TO THE add FUNCTION
def add(a, b, c): #HERE WE DEFINE A SIMPLE FUNCTION TO ADD THREE NUMBERS
    return a + b + c # RETURNS THE SUM OF a, b, AND c / WE RETURN TO SHOW THAT THE DECORATOR DOESN'T INTERFERE WITH THE FUNCTIONALITY


# THE FOLLOWING EXAMPLES SHOW HOW THE DECORATOR WORKS PERFECTLY WITH VALID INPUTS
# AND WOULD RAISE ERRORS WITH INVALID ONES
print(add(10, 5, 3))           # = 18
print(add(4.5, 2.0, 1))        # = 7.5

#ANOTHER WAY TO PUT CALL THE FUNCTION, USING A VARIABLE (LONGER VERSION OF print(add(10, 5, 3)) TO SHOW THAT THE DECORATOR DOESN'T INTERFERE WITH NORMAL USAGE)
result = add(1, 2, 3)          # = 6    
print(result)                   # = 6


result = add(10, 47, 29)         # = 86
print(result)                   # = 86
#SAME AS print(add(1, 2, 3)) BUT STORED IN A VARIABLE FIRST, TO SHOW THAT THE DECORATOR....
# DOESN'T INTERFERE WITH THE NORMAL USAGE OF THE FUNCTION



# These will raise TypeError (with clear messages)

print(add(10, "hello", 5))          # = TypeError: All parameters must be numbers! Found: hello (type: str)
print(add(20, 30, None))             # = TypeError: All parameters must be numbers! Found: None (type: NoneType)
print(add(1, 2, [10, 20]))           # = TypeError: All parameters must be numbers! Found: [10, 20] (type: list)