# main.py
"""
Main entry point for the Personal Finance Manager.
This is the file to be run to start the application.
This can be considered the start button for the entire project, initializing the main window and launching the UI.
"""

import sys # HERE WE ARE IMPORTING THE SYS MODULE TO MANAGE THE PYTHON PATH, ALLOWING US TO IMPORT MODULES FROM OTHER DIRECTORIES IN THE PROJECT.
import os # HERE WE ARE IMPORTING THE OS MODULE TO INTERACT WITH THE OPERATING SYSTEM, SPECIFICALLY TO MANAGE FILE PATHS AND DIRECTORIES.

# Add the current directory to Python path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__))) # THIS LINE ADDS THE CURRENT DIRECTORY (WHERE main.py IS LOCATED) 
#TO THE PYTHON PATH. THIS ALLOWS US TO IMPORT MODULES FROM THIS DIRECTORY AND ITS 
# SUBDIRECTORIES WITHOUT ISSUES, ENSURING THAT ALL COMPONENTS OF THE APPLICATION CAN BE ACCESSED PROPERLY.

from ui.main_window import MainWindow # HERE WE ARE IMPORTING THE MainWindow CLASS FROM THE ui.main_window MODULE. 
#THIS CLASS IS RESPONSIBLE FOR MANAGING THE MAIN APPLICATION WINDOW AND ITS INTERACTIONS.


def main(): # THIS IS THE MAIN FUNCTION THAT SERVES AS THE ENTRY POINT OF THE APPLICATION.
    print("Starting Personal Finance Manager...") # THIS PRINT STATEMENT IS A SIMPLE LOG TO INDICATE THAT THE APPLICATION IS STARTING.
    app = MainWindow() # HERE WE ARE CREATING AN INSTANCE OF THE MainWindow CLASS, WHICH INITIALIZES THE MAIN WINDOW OF THE APPLICATION AND SETS UP THE USER INTERFACE.
    app.run() # THIS LINE CALLS THE run() METHOD OF THE MainWindow INSTANCE, WHICH STARTS THE APPLICATION'S EVENT LOOP, ALLOWING THE USER TO INTERACT WITH THE UI AND USE THE FEATURES OF THE


if __name__ == "__main__": # THIS CHECK ENSURES THAT THE main() FUNCTION IS ONLY CALLED WHEN THIS SCRIPT IS RUN DIRECTLY, AND NOT WHEN IT IS IMPORTED AS A MODULE IN ANOTHER SCRIPT.
    main() # IF THIS SCRIPT IS THE MAIN PROGRAM BEING EXECUTED, THE main() FUNCTION WILL BE CALLED, STARTING THE APPLICATION.