#FIRST I MUST CREATE THE LISTS TO BE USED BY THE DICTIONARY
list1 = ["FIRST_NAME", "LAST_NAME", "AGE", "CITY", "COUNTRY", "OCCUPATION"]
list2 = ["CHARLIE", "MANSON", 25, "ROMA", "ITALY", "BAKER"]

#NOW I CREATE THE DICTIONARY
dictionary = {}
#THIS IS THE CYCLE THAT WILL CREATE THE DICTIONARY
for i in range(len(list1)):
    dictionary[list1[i]] = list2[i]

#PRINT THE DICTIONARY (KEYS AND VALUES) IN OTHER WORDS, THE RESULTS
print(dictionary)

