import math  # Necesario para usar math.pi

class Circle: # CLASS DEFINITION
    def __init__(self, radius): # CONSTRUCTOR THAT TAKES RADIUS AS A PARAMETER/VARIABLE
        self.radius = radius  # HERE i AM TAKING THE VARIABLE RADIUS FROM THE CONSTRUCTOR AND CONVERTING IT TO AN ATTRIBUTE OF THE CLASS
    
    def get_area(self):
        return math.pi * self.radius ** 2  # THIS IS FIXED MATH FORMULA (NON-VARIABLE) THAT CALCULATES THE AREA OF A CIRCLE

#FOLLOWING THE ANALOGY OF A BAKERY THIS WOULD BE THE FIRST MOULD/PATTERN TO MAKE A CIRCLE CAKE
# WHERE THE RADIUS IS VARIABLE/CHANGEABLE DEPENDING ON THE ORDER
my_circle = Circle(10)  # MY CIRCLE HAS A RADIUS OF 10 FROM THE CLASS/CONSTRUCTOR (PATTERN/MOULD)
print(my_circle.get_area())  #PRINTS THE CALCULATED AREA

# NOW I CAN MAKE ANOTHER CIRCLE WITH A DIFFERENT RADIUS 
# USING THE SAME CLASS/CONSTRUCTOR (PATTERN/MOULD)
# like MAKING ANOTHER CAKE WITH A DIFFERENT SIZE
another_circle = Circle(5)  # ANOTHER CIRCLE WITH A RADIUS OF 5
print(another_circle.get_area())  #PRINTS THE CALCULATED AREA FOR THE NEW CIRCLE

# THIS DEMONSTRATES HOW A CLASS CAN BE USED TO CREATE MULTIPLE OBJECTS WITH DIFFERENT ATTRIBUTES