#FIRST WE ARE CREATING 6 DIFFERENT CLASSES FOR THE HUMAN BODY PARTS: HEAD, HAND, FOOT, ARM, LEG, TORSO.
#THE TORSO CLASS WILL CONTAIN INSTANCES OF THE OTHER BODY PART CLASSES TO REPRESENT A COMPLETE HUMAN BODY STRUCTURE.
#THE HUMAN CLASS WILL THEN COMBINE ALL THESE PARTS TO FORM A COMPLETE HUMAN BEING.

"""THIS IS A MODULE DEFINING THE STRUCTURE OF A HUMAN BODY USING CLASSES TO REPRESENT DIFFERENT BODY PARTS."""
"""FOLLOWING THE ANALOGY OF A MOULD, FACTORY, THIS WOULD BE THE MOULD FOR THE HUMAN BODY PARTS."""
class Head: #MOULD FOR THE HEAD PART OF THE HUMAN BODY
    def __init__(self):
        pass
    
    def __str__(self): # STRING REPRESENTATION OF THE HEAD CLASS, THIS WILL HELP IN PRINTING THE OBJECT IN A READABLE FORMAT.
        return "Head"


class Hand:#MOULD FOR THE HAND PART OF THE HUMAN BODY
    def __init__(self):
        pass
    
    def __str__(self):
        return "Hand"


class Foot: #MOULD FOR THE FOOT PART OF THE HUMAN BODY
    def __init__(self):
        pass
    
    def __str__(self):
        return "Foot"


class Arm:#MOULD FOR THE ARM PART OF THE HUMAN BODY
    def __init__(self, hand: Hand):
        self.hand = hand  # An arm has one hand
    
    def __str__(self):
        return f"Arm with {self.hand}"


class Leg: #MOULD FOR THE LEG PART OF THE HUMAN BODY
    def __init__(self, foot: Foot):
        self.foot = foot  # A leg has one foot
    
    def __str__(self):
        return f"Leg with {self.foot}"


class Torso: #MOULD FOR THE TORSO PART OF THE HUMAN BODY
    def __init__(self, head: Head, left_arm: Arm, right_arm: Arm, left_leg: Leg, right_leg: Leg): #A TORSO HAS A HEAD, TWO ARMS, AND TWO LEGS
        self.head = head #THE TORSO CONTAINS THE HEAD, WHICH IS WHY IT IS PASSED AS A PARAMETER/ATTRIBUTE TO THE TORSO CLASS
        self.left_arm = left_arm #THE TORSO CONTAINS AN ARM, WHICH IS WHY IT IS PASSED AS A PARAMETER/ATTRIBUTE TO THE TORSO CLASS
        self.right_arm = right_arm #THE TORSO CONTAINS AN ARM, WHICH IS WHY IT IS PASSED AS A PARAMETER/ATTRIBUTE TO THE TORSO CLASS
        self.left_leg = left_leg #THE TORSO CONTAINS A LEG, WHICH IS WHY IT IS PASSED AS A PARAMETER/ATTRIBUTE TO THE TORSO CLASS
        self.right_leg = right_leg #THE TORSO CONTAINS A LEG, WHICH IS WHY IT IS PASSED AS A PARAMETER/ATTRIBUTE TO THE TORSO CLASS
    
    def __str__(self): # STRING REPRESENTATION OF THE TORSO CLASS, THIS WILL HELP IN PRINTING THE OBJECT IN A READABLE FORMAT.
        return (f"Torso with:\n" # PRINTS ALL THE BODY PARTS CONTAINED IN THE TORSO
                f"  - {self.head}\n" # PRINTS THE HEAD PART WITH A DASH FOR BETTER READABILITY AND A NEW LINE "\n"
                f"  - {self.left_arm}\n" # PRINTS THE LEFT ARM PART WITH A DASH FOR BETTER READABILITY AND A NEW LINE "\n"
                f"  - {self.right_arm}\n" # PRINTS THE RIGHT ARM PART WITH A DASH FOR BETTER READABILITY AND A NEW LINE "\n"
                f"  - {self.left_leg}\n" # PRINTS THE LEFT LEG PART WITH A DASH FOR BETTER READABILITY AND A NEW LINE "\n"
                f"  - {self.right_leg}") # PRINTS THE RIGHT LEG PART WITH A DASH FOR BETTER READABILITY AND A NEW LINE "\n"


class Human: #MOULD FOR THE COMPLETE HUMAN BODY
    #FIRST WE DEFINE THE __INIT__ METHOD TO INITIALIZE THE HUMAN OBJECT WITH A NAME AND A TORSO THAT CONTAINS ALL BODY PARTS
    def __init__(self, name: str, head: Head, left_arm: Arm, right_arm: Arm, left_leg: Leg, right_leg: Leg):
        self.name = name #HERE WE SET THE NAME OF THE HUMAN
        # SINCE A HUMAN IS COMPRISED OF A TORSO THAT CONTAINS ALL THE BODY PARTS, WE CREATE AN INSTANCE OF THE TORSO CLASS
        self.torso = Torso(head, left_arm, right_arm, left_leg, right_leg) #HERE WE INITIALIZE THE TORSO WITH THE PROVIDED BODY PARTS
    
    def __str__(self): # STRING REPRESENTATION OF THE HUMAN CLASS, THIS WILL HELP IN PRINTING THE OBJECT IN A READABLE FORMAT.
        return f"Human: {self.name}\n{self.torso}" # PRINTS THE NAME OF THE HUMAN AND THE STRING REPRESENTATION OF THE TORSO WHICH INCLUDES ALL BODY PARTS

"""THIS IS THE THE SECOND PART OF THE MODULE/CODE WHERE WE CREATE INSTANCES (OBJECTS) OF THE CLASSES "MOULDS" DEFINED ABOVE TO FORM A COMPLETE HUMAN BODY STRUCTURE."""
# HERE WE CALL THE CLASSES TO CREATE A COMPLETE HUMAN BODY STRUCTURE AND PRINT IT OUT
if __name__ == "__main__": #THIS BLOCK ENSURES THAT THE CODE BELOW RUNS ONLY WHEN THIS FILE IS EXECUTED DIRECTLY, NOT WHEN IMPORTED AS A MODULE.
    # WE CREATE INDIVIDUAL BODY PARTS
    #WE CREATE INSTANCES OF EACH BODY PART CLASS, WHICH REPRESENTS THE ACT OF MANUFACTURING OR ASSEMBLING EACH PART.
    head = Head()
    
    left_hand = Hand()
    right_hand = Hand()
    
    left_foot = Foot()
    right_foot = Foot()
    
    # CREATING ARMS AND LEGS (LIMBS) OUT OF HANDS AND FEET
    # A CONNECTION IS MADE BETWEEN THE LIMBS AND THEIR RESPECTIVE PARTS (HANDS AND FEET) BY PASSING THE HAND AND FOOT OBJECTS AS PARAMETERS TO THE ARM AND LEG CLASSES.
    left_arm = Arm(left_hand) #LEFT ARM CONTAINS LEFT HAND, WHICH IS PASSED AS A PARAMETER TO THE ARM CLASS 
    right_arm = Arm(right_hand) #RIGHT ARM CONTAINS RIGHT HAND, WHICH IS PASSED AS A PARAMETER TO THE ARM CLASS
    
    left_leg = Leg(left_foot) #LEFT LEG CONTAINS LEFT FOOT, WHICH IS PASSED AS A PARAMETER TO THE LEG CLASS
    right_leg = Leg(right_foot) #RIGHT LEG CONTAINS RIGHT FOOT, WHICH IS PASSED AS A PARAMETER TO THE LEG CLASS
    
    # WE FINALLY CREATE A HUMAN BEING BY COMBINING ALL THE BODY PARTS
    # THE HUMAN CLASS IS INSTANTIATED WITH A NAME AND ALL THE BODY PARTS TO FORM A COMPLETE HUMAN STRUCTURE.
    # THE HUMAN OBJECT IS CALLED "person" AND IS INITIALIZED WITH THE NAME "Alice" AND ALL THE BODY PARTS CREATED ABOVE.
    person = Human("Alice", head, left_arm, right_arm, left_leg, right_leg)
    
    # DISPLAY THE COMPLETE HUMAN STRUCTURE
    print(person) # THIS PRINTS THE STRING REPRESENTATION OF THE HUMAN OBJECT, WHICH INCLUDES THE NAME AND ALL BODY PARTS.