# =======================================================
# VERY SIMPLE STACK IMPLEMENTATION USING LINKED NODES
# NO LISTS, NO TUPLES, NO DICTS, NO COLLECTIONS ALLOWED
# =======================================================

# ────────────────────────────────────────────────
# CLASS 1: NODE
# THIS IS THE SMALLEST PIECE OF THE STACK
# EACH NODE HOLDS ONE VALUE AND ONE POINTER TO NEXT
# ────────────────────────────────────────────────
class Node:
    def __init__(self, value):
        self.value = value # THE ACTUAL DATA WE WANT TO STORE (NUMBER, STRING, WHATEVER)
        self.next = None # POINTER TO THE NEXT NODE (OR NONE IF IT IS THE LAST ONE)
                        # VERY IMPORTANT: THIS CREATES THE CHAIN/LINKED STRUCTURE
                        #IN THIS CASE WE SET THE NEXT TO NONE BECAUSE WHEN WE CREATE A NEW NODE, IT IS NOT CONNECTED TO ANYTHING YET


# ────────────────────────────────────────────────
# CLASS 2: STACK
# THE STACK ITSELF – ONLY KEEPS TRACK OF THE TOP NODE
# EVERYTHING ELSE IS CONNECTED THROUGH .NEXT POINTERS
# ────────────────────────────────────────────────
class Stack:
    
    def __init__(self):
        # THIS IS THE MOST IMPORTANT VARIABLE, BECAUSE ONCE THE STACK STARTS TO GROW, WE ONLY CARE ABOUT THE TOP NODE
        # IT POINTS TO THE TOP ELEMENT OF THE STACK
        # WHEN STACK IS EMPTY → SELF.TOP = NONE
        self.top = None
    
    
    # ───────────────────────────────
    # PUSH (FUNCTION): ADD NEW ELEMENT ON TOP
    # ───────────────────────────────
    def push(self, value): #HERE WE ARE CREATING A NEW NODE WITH THE VALUE WE WANT TO ADD TO THE STACK (WE ARE NOT USING A LIST TO STORE THE VALUES, INSTEAD WE ARE CREATING A LINKED STRUCTURE WITH NODES)
        new_node = Node(value) # STEP 1: CREATE A BRAND NEW NODE WITH THE VALUE
        
        # STEP 2: MAKE THE NEW NODE POINT TO WHATEVER WAS THE TOP BEFORE
        #         (THIS CONNECTS THE NEW NODE TO THE REST OF THE STACK)
        new_node.next = self.top # STEP 3: NOW THE NEW NODE BECOMES THE OFFICIAL TOP OF THE STACK
        self.top = new_node # RESULT: NEW ITEM IS NOW FIRST IN LINE (LIFO BEHAVIOR)
    
    
    # ───────────────────────────────
    # POP (FUNCTION: REMOVE AND RETURN TOP ITEM
    # ───────────────────────────────
    def pop(self):
        # SAFETY CHECK: IS THE STACK EMPTY? - WE ARE ADDING THIS AS A PREVENTION NET TO AVOID CRASHING THE PROGRAM IF SOMEONE TRIES TO POP FROM AN EMPTY STACK
        if self.top is None:
            # VERY IMPORTANT: NEVER TRY TO POP FROM EMPTY STACK
            print("ERROR: CANNOT POP FROM AN EMPTY STACK!")
            return None # WE RETURN NONE TO INDICATE THAT THERE WAS NO VALUE TO POP (THIS IS A DESIGN CHOICE, WE COULD ALSO RAISE AN EXCEPTION OR HANDLE IT DIFFERENTLY, BUT FOR SIMPLICITY WE JUST PRINT AN ERROR AND RETURN NONE)
        
        # STEP 1: REMEMBER THE VALUE WE ARE GOING TO RETURN
        value_to_return = self.top.value # WE SAVE THE VALUE OF THE CURRENT TOP NODE BEFORE WE CHANGE ANYTHING, BECAUSE ONCE WE MOVE THE TOP POINTER, WE WOULD LOSE ACCESS TO THAT VALUE IF WE DIDN'T SAVE IT FIRST
        
        # STEP 2: MOVE THE TOP POINTER ONE POSITION DOWN THE CHAIN
        self.top = self.top.next #         NOW TOP POINTS TO THE SECOND ELEMENT (OR NONE)
        
        # STEP 3: GIVE BACK THE VALUE THAT WAS REMOVED
        return value_to_return # THIS IS THE VALUE OF THE NODE THAT WAS JUST REMOVED FROM THE TOP OF THE STACK, THIS IS LIKE THE "OUTPUT" OF THE POP FUNCTION, IT LETS THE USER KNOW WHAT VALUE WAS REMOVED FROM THE STACK
    
    
    # ───────────────────────────────
    # PRINT: SHOW ALL ELEMENTS FROM TOP TO BOTTOM
    # ───────────────────────────────
    def print_stack(self): #THIS IS LIKE A PEEK FUNCTION THAT LETS US SEE WHAT IS CURRENTLY IN THE STACK WITHOUT MODIFYING IT, IT TRAVERSAL THE STACK FROM TOP TO BOTTOM AND PRINTS THE VALUES IN ORDER
        if self.top is None: # SAFETY CHECK: IF THE STACK IS EMPTY, WE JUST PRINT A MESSAGE AND RETURN (THIS IS OPTIONAL, BUT IT MAKES IT CLEAR TO THE USER THAT THERE IS NOTHING TO SHOW)
            print("STACK IS EMPTY → NOTHING TO SHOW") # FRIENDLY MESSAGE TO INDICATE THAT THE STACK IS EMPTY
            return # WE EXIT THE FUNCTION EARLY BECAUSE THERE IS NOTHING TO PRINT
        
        # HEADER SO IT IS EASY TO READ
        print("STACK (FROM TOP TO BOTTOM):") # THIS IS JUST A TITLE TO MAKE IT CLEAR WHAT WE ARE PRINTING, IT HELPS TO ORGANIZE THE OUTPUT AND MAKE IT MORE READABLE
        
        # WE START AT THE TOP AND FOLLOW .NEXT UNTIL WE REACH NONE
        current = self.top #THIS MIGHT BE A BIT CONFUSING, BUT WE ARE CREATING A TEMPORARY VARIABLE CALLED CURRENT THAT STARTS AT THE TOP OF THE STACK, THIS IS NECESSARY BECAUSE WE DON'T WANT TO MODIFY SELF.TOP, WE JUST WANT TO TRAVERSE THE STACK WITHOUT CHANGING ITS STRUCTURE, SO WE USE CURRENT AS A POINTER TO WALK THROUGH THE STACK
        
        while current is not None: #WE ARE USING A WHILE LOOP BECAUSE WE DON'T KNOW IN ADVANCE HOW MANY NODES THERE ARE IN THE STACK, WE JUST KEEP GOING UNTIL WE REACH THE END (WHEN CURRENT BECOMES NONE)
            # SHOW INDENTATION + VALUE
            print("   →", current.value)
            # MOVE TO THE NEXT NODE IN THE CHAIN
            current = current.next
        
        # NICE SEPARATOR LINE
        print("───────────────────────────────")


# ────────────────────────────────────────────────
#               EXAMPLE USAGE + TESTS
# ────────────────────────────────────────────────

print("CREATING A NEW EMPTY STACK...\n")
pile = Stack() # THIS IS HOW WE CREATE A NEW STACK, IT STARTS EMPTY WITH TOP = NONE

#NEXT LINE IS HOW WE CALL THE PRINT FUNCTION TO SEE WHAT IS IN THE STACK, SINCE WE JUST CREATED IT AND DIDN'T ADD ANY ELEMENTS, IT SHOULD SHOW A MESSAGE INDICATING THAT THE STACK IS EMPTY
pile.print_stack() # THIS SHOULD SHOW A MESSAGE INDICATING THAT THE STACK IS EMPTY, BECAUSE WE JUST CREATED IT AND NO ELEMENTS HAVE BEEN ADDED YET

print("\nPUSHING SOME NUMBERS...\n")
pile.push(10) # THIS IS HOW WE ADD ELEMENTS TO THE STACK, WE CALL THE PUSH FUNCTION WITH THE VALUE WE WANT TO ADD, IN THIS CASE WE ARE ADDING 10, THEN 20, THEN 35, THEN 99, EACH TIME WE CALL PUSH, A NEW NODE IS CREATED AND ADDED TO THE TOP OF THE STACK    
pile.push(20) #THIS WOULD BE THE SECOND ELEMENT IN THE STACK, BUT IT WILL BE BELOW 10 BECAUSE 10 WAS ADDED FIRST, REMEMBER THIS IS A LIFO STRUCTURE, SO THE LAST ONE ADDED (20) WILL BE ON TOP OF THE ONE ADDED BEFORE (10)
pile.push(35) #THIS WOULD BE THE THIRD ELEMENT IN THE STACK, BUT IT WILL BE BELOW 20 AND 10 BECAUSE 20 WAS ADDED BEFORE AND 10 WAS ADDED FIRST, REMEMBER THIS IS A LIFO STRUCTURE, SO THE LAST ONE ADDED (35) WILL BE ON TOP OF THE ONES ADDED BEFORE (20 AND 10)
pile.push(99) #THIS WOULD BE THE FOURTH ELEMENT IN THE STACK, BUT IT WILL BE BELOW 35, 20, AND 10 BECAUSE 35 WAS ADDED BEFORE, THEN 20, THEN 10, REMEMBER THIS IS A LIFO STRUCTURE, SO THE LAST ONE ADDED (99) WILL BE ON TOP OF THE ONES ADDED BEFORE (35, 20, AND 10)

pile.print_stack() #HERE WE CALL THE PRINT FUNCTION AGAIN TO SEE WHAT IS CURRENTLY IN THE STACK, IT SHOULD SHOW THE VALUES IN LIFO ORDER (99 ON TOP, THEN 35, THEN 20, THEN 10)

print("\nPOPPING TWO ELEMENTS...\n")
print("REMOVED →", pile.pop())   # HERE WE CALL THE POP FUNCTION TO REMOVE THE TOP ELEMENT OF THE STACK, IT SHOULD RETURN 99 FIRST BECAUSE IT WAS THE LAST ONE ADDED (LIFO), THEN 35 ON THE SECOND CALL TO POP
print("REMOVED →", pile.pop())   # THE SECOND CALL TO POP SHOULD RETURN 35 BECAUSE IT WAS THE SECOND TO LAST ONE ADDED, THEN 20 AND 10 WILL STILL BE IN THE STACK

pile.print_stack() #HERE WE USE THE SAME LOGIC AS BEFORE TO PRINT THE CURRENT STATE OF THE STACK, IT SHOULD SHOW 20 ON TOP AND THEN 10 BELOW IT, BECAUSE 99 AND 35 WERE REMOVED WITH THE POP CALLS

print("\nPUSHING ONE MORE VALUE...\n")
pile.push(777) # THIS WOULD BE THE FIFTH ELEMENT IN THE STACK, BUT IT WILL BE BELOW 20 AND 10 BECAUSE 20 WAS ADDED BEFORE AND 10 WAS ADDED FIRST, REMEMBER THIS IS A LIFO STRUCTURE, SO THE LAST ONE ADDED (777) WILL BE ON TOP OF THE ONES ADDED BEFORE (20 AND 10)

pile.print_stack()

print("\nTRYING TO POP UNTIL EMPTY...\n")
print("REMOVED →", pile.pop())
print("REMOVED →", pile.pop())
print("REMOVED →", pile.pop())     # SHOULD SHOW ERROR
print("REMOVED →", pile.pop())     # AGAIN ERROR

pile.print_stack()