"""ANALOGY: A DEQUE IS LIKE A LINE OF PEOPLE WAITING FOR A SERVICE, WHERE PEOPLE CAN JOIN THE LINE FROM THE FRONT OR THE BACK, AND THEY CAN ALSO LEAVE THE LINE FROM EITHER END, THIS FLEXIBILITY MAKES THE DEQUE A USEFUL DATA STRUCTURE FOR MANAGING COLLECTIONS OF ELEMENTS IN SITUATIONS WHERE WE NEED TO ACCESS BOTH ENDS EFFICIENTLY"""


# NOTE: DEQUE STANDS FOR DOUBLE ENDED QUEUE, IT IS A DATA STRUCTURE THAT ALLOWS INSERTION AND DELETION OF ELEMENTS FROM BOTH ENDS (FRONT AND BACK)
# THIS IS USEFUL IN SITUATIONS WHERE WE WANT TO MAINTAIN A COLLECTION OF ELEMENTS AND WE WANT TO BE ABLE TO ADD OR REMOVE ELEMENTS EFFICIENTLY FROM EITHER END OF THE COLLECTION, DEQUEs ARE OFTEN USED IN ALGORITHMS THAT REQUIRE A QUEUE-LIKE STRUCTURE BUT ALSO NEED TO ACCESS BOTH ENDS OF THE QUEUE, SUCH AS BREADTH-FIRST SEARCH (BFS) OR SLIDING WINDOW PROBLEMS
# IN THIS IMPLEMENTATION, WE WILL USE A DOUBLY LINKED LIST TO REPRESENT THE DEQUE, WHERE EACH NODE HAS A POINTER TO THE NEXT NODE AND A POINTER TO THE PREVIOUS NODE, THIS ALLOWS US TO EFFICIENTLY ADD OR REMOVE NODES FROM EITHER END OF THE DEQUE WITHOUT HAVING TO SHIFT ELEMENTS (AS WE WOULD IN AN ARRAY-BASED IMPLEMENTATION)
#----------------------------------------------------------------------------------------------
# DEFINE THE NODE CLASS WHICH WILL HOLD THE DATA AND POINTERS TO NEXT AND PREVIOUS NODES
# THIS IS THE BASIC BUILDING BLOCK OF THE DEQUE, EACH NODE CAN BE LINKED TO ANOTHER NODE THROUGH THE NEXT AND PREVIOUS POINTERS
# WE ARE USING A DOUBLY LINKED NODE BECAUSE WE WANT TO BE ABLE TO TRAVERSE IN BOTH DIRECTIONS (FROM HEAD TO TAIL AND FROM TAIL TO HEAD) IN THE DEQUE

"""------>> FIRST STEP: DEFINE THE NODE CLASS <<------"""
class Node: # HERE WE ARE DEFINING THE NODE CLASS, THIS CLASS WILL BE USED TO CREATE NODES THAT HOLD THE DATA AND THE POINTERS TO THE NEXT AND PREVIOUS NODES IN THE DEQUE, THIS IS A DOUBLY LINKED NODE BECAUSE IT HAS BOTH NEXT AND PREVIOUS POINTERS, THIS ALLOWS US TO EFFICIENTLY ADD OR REMOVE NODES FROM EITHER END OF THE DEQUE WITHOUT HAVING TO SHIFT ELEMENTS (AS WE WOULD IN AN ARRAY-BASED IMPLEMENTATION)
    # INITIALIZE THE NODE WITH DATA, NEXT POINTER AS NONE, AND PREVIOUS POINTER AS NONE
    def __init__(self, data):
        self.data = data # SET THE DATA ATTRIBUTE OF THE NODE TO THE VALUE PASSED IN THE CONSTRUCTOR, THIS CAN BE ANY TYPE OF DATA (NUMBER, STRING, OBJECT, ETC.) THAT WE WANT TO STORE IN THE DEQUE
        self.next = None # SET THE NEXT POINTER TO NONE INDICATING NO NEXT NODE YET
        self.prev = None # SET THE PREVIOUS POINTER TO NONE INDICATING NO PREVIOUS NODE YET


"""------>> SECOND STEP: DEFINE THE DEQUE CLASS <<------"""
# THIS CLASS HOLDS THE CONSTRUCTOR TO INITIALIZE THE DEQUE AND 5 DIFFERENT METHODS TO MANAGE THE DEQUE:
# (PUSH_LEFT, PUSH_RIGHT, POP_LEFT, POP_RIGHT, PRINT_DEQUE)
# PRINT_DEQUE >>>> IS A HELPER METHOD TO VISUALIZE THE CURRENT STATE OF THE DEQUE, IT TRAVERSAL FROM HEAD TO TAIL AND PRINTS THE DATA OF EACH NODE IN SEQUENCE, THIS IS USEFUL FOR DEBUGGING AND UNDERSTANDING HOW THE DEQUE CHANGES WITH EACH OPERATION

# DEFINE THE DEQUE CLASS WHICH WILL MANAGE THE DOUBLE ENDED QUEUE USING HEAD AND TAIL POINTERS
class Deque:
    def __init__(self): # INITIALIZE THE DEQUE WITH HEAD AND TAIL AS NONE SINCE IT STARTS EMPTY
        self.head = None # SET THE HEAD POINTER TO NONE FOR AN EMPTY DEQUE
        self.tail = None # SET THE TAIL POINTER TO NONE FOR AN EMPTY DEQUE

    # DEFINE THE PUSH_LEFT METHOD TO ADD A NEW NODE AT THE BEGINNING OF THE DEQUE
    def push_left(self, data):
        new_node = Node(data) # CREATE A NEW NODE WITH THE GIVEN DATA, THIS NODE WILL BE ADDED TO THE FRONT OF THE DEQUE
        if self.head is None: # CHECK IF THE DEQUE IS EMPTY BY SEEING IF HEAD IS NONE (SAFETY CHECK TO AVOID ERRORS WHEN TRYING TO ACCESS PROPERTIES OF NONE)
            self.head = new_node # IF EMPTY, SET HEAD TO THE NEW NODE
            self.tail = new_node # ALSO SET TAIL TO THE NEW NODE SINCE THERE'S ONLY ONE NODE

            """  new_node.next = self.head >> THIS LINE TELLS THE CURRENT HEAD THAT IT IS BEING PUSHED TO THE LEFT, SO THE NEW NODE WILL BE THE NEW HEAD, AND THE CURRENT HEAD WILL BE THE SECOND NODE IN THE DEQUE, THIS IS LIKE SAYING "HEY CURRENT HEAD, YOU ARE NOW SECOND IN LINE BECAUSE THIS NEW NODE IS GOING TO BE FIRST IN LINE" """
            
        else: # IF NOT EMPTY, PROCEED TO ADD AT THE FRONT
            new_node.next = self.head # LINK THE NEW NODE'S NEXT TO THE CURRENT HEAD (THIS CONNECTS THE NEW NODE TO THE REST OF THE DEQUE)
            self.head.prev = new_node # LINK THE CURRENT HEAD'S PREVIOUS TO THE NEW NODE
            self.head = new_node # UPDATE HEAD TO POINT TO THE NEW NODE, THIS MAKES THE NEW NODE THE FIRST ELEMENT IN THE DEQUE, THIS IS LIKE ENSURING THAT THE NEW NODE HOLDS HANDS WITH THE CURRENT HEAD AND THEN BECOMES THE NEW HEAD OF THE DEQUE

    # DEFINE THE PUSH_RIGHT METHOD TO ADD A NEW NODE AT THE END OF THE DEQUE
    def push_right(self, data):
        new_node = Node(data) # CREATE A NEW NODE WITH THE GIVEN DATA, THIS NODE WILL BE ADDED TO THE END OF THE DEQUE
        if self.tail is None: # CHECK IF THE DEQUE IS EMPTY BY SEEING IF TAIL IS NONE (SAFETY CHECK TO AVOID ERRORS WHEN TRYING TO ACCESS PROPERTIES OF NONE)
            self.head = new_node # IF EMPTY, SET HEAD TO THE NEW NODE
            self.tail = new_node # ALSO SET TAIL TO THE NEW NODE SINCE THERE'S ONLY ONE NODE
            
        else: # IF NOT EMPTY, PROCEED TO ADD AT THE END
            new_node.prev = self.tail # LINK THE NEW NODE'S PREVIOUS TO THE CURRENT TAIL (THIS CONNECTS THE NEW NODE TO THE REST OF THE DEQUE)
            self.tail.next = new_node # LINK THE CURRENT TAIL'S NEXT TO THE NEW NODE
            self.tail = new_node # UPDATE TAIL TO POINT TO THE NEW NODE, THIS MAKES THE NEW NODE THE LAST ELEMENT IN THE DEQUE, THIS IS LIKE ENSURING THAT THE NEW NODE HOLDS HANDS WITH THE CURRENT TAIL AND THEN BECOMES THE NEW TAIL OF THE DEQUE

    # DEFINE THE POP_LEFT METHOD TO REMOVE AND RETURN THE NODE FROM THE BEGINNING
    def pop_left(self):
        if self.head is None: # CHECK IF THE DEQUE IS EMPTY BY SEEING IF HEAD IS NONE (SAFETY CHECK TO AVOID ERRORS WHEN TRYING TO ACCESS PROPERTIES OF NONE)
            return None # IF EMPTY, RETURN NONE SINCE NOTHING TO POP (THIS IS A DESIGN CHOICE, WE COULD ALSO RAISE AN EXCEPTION OR HANDLE IT DIFFERENTLY, BUT FOR SIMPLICITY WE JUST RETURN NONE)
        data = self.head.data # STORE THE DATA OF THE HEAD NODE TO RETURN LATER (IT'S IMPORTANT TO SAVE THIS BEFORE WE CHANGE THE HEAD POINTER, BECAUSE ONCE WE MOVE THE HEAD POINTER, WE WOULD LOSE ACCESS TO THAT DATA IF WE DIDN'T SAVE IT FIRST)
        
        """ THIS LINE "if self.head is not None:" SAYS: IF THERE ARE OTHER NODES LEFT IN THE DEQUE AFTER WE POP THE HEAD, THEN WE NEED TO UPDATE THE NEW HEAD'S PREVIOUS POINTER TO NONE, BECAUSE THE NEW HEAD IS NOW FIRST IN LINE AND DOESN'T HAVE ANYONE IN FRONT OF IT, SO ITS PREVIOUS SHOULD BE NONE. IF THE DEQUE BECOMES EMPTY AFTER POP (THIS HAPPENS WHEN WE POP THE LAST ELEMENT IN THE DEQUE), THEN HEAD WOULD BE NONE, AND WE SHOULD ALSO SET TAIL TO NONE TO INDICATE THAT THE DEQUE IS NOW EMPTY. """
        self.head = self.head.next # SO ONCE THE DATA IS SAVED (WE CAN SAY THAT IT IS REMOVED FROM THE DEQUE), SO WE THEN MOVE THE HEAD POINTER TO THE NEXT NODE IN THE DEQUE, THIS EFFECTIVELY REMOVES THE ORIGINAL HEAD NODE FROM THE DEQUE, BECAUSE NOW THE HEAD POINTER NO LONGER POINTS TO IT, AND IT IS NOT LINKED TO ANY OTHER NODES IN THE DEQUE.
        if self.head is not None: # CHECK IF THE NEW HEAD IS NOT NONE (THIS CHECK IS IMPORTANT BECAUSE IF THE DEQUE BECOMES EMPTY AFTER POP, THEN HEAD WOULD BE NONE, AND WE SHOULD NOT TRY TO ACCESS PROPERTIES OF NONE)
            self.head.prev = None # IF NOT, SET THE NEW HEAD'S PREVIOUS TO NONE, THIS IS LIKE SAYING "HEY NEW HEAD, YOU ARE NOW FIRST IN LINE, SO YOU DON'T HAVE ANYONE IN FRONT OF YOU, SO YOUR PREVIOUS SHOULD BE NONE"
        
        else: # IF THE DEQUE BECOMES EMPTY AFTER POP (THIS HAPPENS WHEN WE POP THE LAST ELEMENT IN THE DEQUE, THEN HEAD WOULD BE NONE, AND WE SHOULD ALSO SET TAIL TO NONE TO INDICATE THAT THE DEQUE IS NOW EMPTY)
            self.tail = None # SET TAIL TO NONE AS WELL
        return data # RETURN THE POPPED DATA, THIS IS THE VALUE OF THE NODE THAT WAS JUST REMOVED FROM THE FRONT OF THE DEQUE, THIS IS LIKE THE "OUTPUT" OF THE POP_LEFT FUNCTION, IT LETS THE USER KNOW WHAT VALUE WAS REMOVED FROM THE DEQUE

    # DEFINE THE POP_RIGHT METHOD TO REMOVE AND RETURN THE NODE FROM THE END
    def pop_right(self):
        if self.tail is None: # CHECK IF THE DEQUE IS EMPTY BY SEEING IF TAIL IS NONE (SAFETY CHECK TO AVOID ERRORS WHEN TRYING TO ACCESS PROPERTIES OF NONE)
            return None # IF IT IS IN FACT EMPTY, THEN RETURN NONE SINCE THERE'S NOTHING TO POP
        data = self.tail.data # STORE THE DATA OF THE TAIL NODE TO RETURN LATER (IT'S IMPORTANT TO SAVE THIS BEFORE WE CHANGE THE TAIL POINTER, BECAUSE ONCE WE MOVE THE TAIL POINTER, WE WOULD LOSE ACCESS TO THAT DATA IF WE DIDN'T SAVE IT FIRST)
        
        self.tail = self.tail.prev # MOVE TAIL TO THE PREVIOUS NODE IN THE DEQUE, THIS EFFECTIVELY REMOVES THE ORIGINAL TAIL NODE FROM THE DEQUE, BECAUSE NOW THE TAIL POINTER NO LONGER POINTS TO IT, AND IT IS NOT LINKED TO ANY OTHER NODES IN THE DEQUE.
        if self.tail is not None: # CHECK IF THE NEW TAIL IS NOT NONE
            self.tail.next = None # IF NOT, SET THE NEW TAIL'S NEXT TO NONE, THIS IS LIKE SAYING "HEY NEW TAIL, YOU ARE NOW LAST IN LINE, SO YOU DON'T HAVE ANYONE BEHIND YOU, SO YOUR NEXT SHOULD BE NONE"
        
        else: # IF THE DEQUE BECOMES EMPTY AFTER POP
            self.head = None # SET HEAD TO NONE AS WELL
        return data # RETURN THE POPPED DATA

    # DEFINE THE PRINT_DEQUE METHOD TO PRINT ALL ELEMENTS FROM HEAD TO TAIL
    # HERE WE ARE STARTING FROM THE HEAD NODE AND LOOPING THROUGH EACH NODE UNTIL WE REACH THE END OF THE DEQUE (WHEN CURRENT BECOMES NONE), FOR EACH NODE, WE PRINT ITS DATA FOLLOWED BY A SPACE, AND THEN MOVE TO THE NEXT NODE, ONCE WE HAVE PRINTED ALL NODES, WE PRINT A NEWLINE FOR BETTER FORMATTING
    def print_deque(self):
        current = self.head # START FROM THE HEAD NODE
        while current: # LOOP THROUGH EACH NODE UNTIL CURRENT BECOMES NONE
            print(current.data, end=' ') # PRINT THE DATA OF THE CURRENT NODE FOLLOWED BY A SPACE (END=' ' PREVENTS PRINT FROM MOVING TO A NEW LINE AFTER EACH PRINT, INSTEAD IT KEEPS PRINTING ON THE SAME LINE SEPARATED BY SPACES)
            current = current.next # MOVE TO THE NEXT NODE
        
        print() # FOR BETTER FORMATTING AND READABILITY, I PRINT A NEWLINE AFTER PRINTING ALL NODES IN THE DEQUE



"""THIRD STEP: EXAMPLE USAGE OF THE DEQUE CLASS TO DEMONSTRATE HOW IT WORKS"""
# ────────────────────────────────────────────────
#              EXAMPLE USAGE
# ────────────────────────────────────────────────

print("=== DEQUE TEST ===")

d = Deque() # WE ARE CREATING A NEW INSTANCE OF THE DEQUE CLASS, THIS WILL INITIALIZE AN EMPTY DEQUE WITH HEAD AND TAIL SET TO NONE, NOW WE CAN USE THIS INSTANCE TO CALL THE METHODS DEFINED IN THE DEQUE CLASS TO MANAGE OUR DOUBLE ENDED QUEUE

# Adding elements to the deque
print("Adding elements...") # WE ARE CALLING THE PUSH_LEFT AND PUSH_RIGHT METHODS TO ADD ELEMENTS TO THE DEQUE, THIS WILL SHOW HOW WE CAN ADD ELEMENTS TO BOTH ENDS OF THE DEQUE, AND HOW THE ORDER OF ELEMENTS CHANGES BASED ON WHETHER WE PUSH LEFT OR RIGHT
d.push_right(10)         # deque: 10
d.push_left(5)           # deque: 5 10
d.push_right(20)         # deque: 5 10 20
d.push_left(3)           # deque: 3 5 10 20 (THIS SHOWS THAT WHEN WE PUSH LEFT, THE NEW ELEMENT BECOMES THE NEW HEAD OF THE DEQUE, AND THE EXISTING ELEMENTS ARE SHIFTED TO THE RIGHT, AND WHEN WE PUSH RIGHT, THE NEW ELEMENT BECOMES THE NEW TAIL OF THE DEQUE, AND THE EXISTING ELEMENTS REMAIN IN PLACE EXCEPT FOR THE TAIL POINTER WHICH NOW POINTS TO THE NEW NODE)
d.push_right(30)         # deque: 3 5 10 20 30

print("Current deque:") # WE CALL THE PRINT_DEQUE METHOD TO SEE THE CURRENT STATE OF THE DEQUE AFTER ADDING ELEMENTS, THIS SHOULD SHOW THE ELEMENTS IN THE ORDER THEY ARE LINKED FROM HEAD TO TAIL, WHICH SHOULD BE 3 5 10 20 30 BASED ON THE PUSH_LEFT AND PUSH_RIGHT CALLS WE MADE
d.print_deque()          # Expected: 3 5 10 20 30

# Remove from the left
print("\nRemoving from left:") # WE ARE CALLING THE POP_LEFT METHOD TO REMOVE ELEMENTS FROM THE FRONT (LEFT) OF THE DEQUE, THIS WILL SHOW HOW WE CAN EFFICIENTLY REMOVE ELEMENTS FROM THE LEFT END OF THE DEQUE, AND HOW THE HEAD POINTER MOVES TO THE NEXT NODE IN THE DEQUE AFTER EACH POP_LEFT CALL, THIS SHOULD ALSO SHOW HOW THE ORDER OF ELEMENTS CHANGES AS WE REMOVE FROM THE LEFT END
print("Removed:", d.pop_left())    # 3
print("Removed:", d.pop_left())    # 5
print("Deque now:")              
d.print_deque()                    # Expected: 10 20 30

# Remove from the right
print("\nRemoving from right:") #FOLLOWING THE SAME LOGIC AS BEFORE, WE ARE CALLING THE POP_RIGHT METHOD TO REMOVE ELEMENTS FROM THE BACK (RIGHT) OF THE DEQUE, THIS WILL SHOW HOW WE CAN EFFICIENTLY REMOVE ELEMENTS FROM THE RIGHT END OF THE DEQUE, AND HOW THE TAIL POINTER MOVES TO THE PREVIOUS NODE IN THE DEQUE AFTER EACH POP_RIGHT CALL, THIS SHOULD ALSO SHOW HOW THE ORDER OF ELEMENTS CHANGES AS WE REMOVE FROM THE RIGHT END
print("Removed:", d.pop_right())   # 30
print("Removed:", d.pop_right())   # 20
print("Deque now:")
d.print_deque()                    # Expected: 10

# Removing the last element
print("\nRemoving last element from left:") # WE ARE CALLING POP_LEFT ONE LAST TIME TO REMOVE THE LAST REMAINING ELEMENT IN THE DEQUE, THIS WILL SHOW HOW THE DEQUE BECOMES EMPTY AFTER REMOVING THE LAST ELEMENT, AND HOW BOTH HEAD AND TAIL POINTERS ARE SET TO NONE TO INDICATE THAT THE DEQUE IS NOW EMPTY
print("Removed:", d.pop_left())    # 10
print("Deque now (should be empty):")
d.print_deque()                    # Expected: (empty line)

# Trying to remove from empty deque
print("\nTrying to remove from empty deque:") # FINALLY, WE ARE CALLING POP_LEFT AND POP_RIGHT ON AN EMPTY DEQUE TO SEE HOW THE METHODS HANDLE THIS CASE, THIS SHOULD RETURN NONE FOR BOTH CALLS SINCE THERE'S NOTHING TO POP, THIS IS A GOOD TEST TO ENSURE THAT OUR METHODS CAN HANDLE EDGE CASES GRACEFULLY WITHOUT RAISING ERRORS
print("pop_left returns:", d.pop_left())    # None
print("pop_right returns:", d.pop_right())  # None

print("\n=== END OF TEST ===")