# DEFINE A CLASS FOR EACH NODE IN THE BINARY TREE
# THIS CLASS WILL HAVE A VALUE AND POINTERS TO LEFT AND RIGHT CHILDREN
# IN THIS IMPLEMENTATION, WE ARE NOT ENFORCING ANY PARTICULAR ORDER OR BALANCE, THIS IS JUST A BASIC STRUCTURE TO REPRESENT A BINARY TREE, WE CAN BUILD MORE COMPLEX TREES BY LINKING NODES TOGETHER USING THE LEFT AND RIGHT POINTERS
# IMPORTANT TO NOTE ALSO THAT WE ARE FIRST CREATING AN EMPTY TREE WITH ROOT = NONE, AND EMPTY NODES WITH LEFT AND RIGHT = NONE, THEN WE CAN MANUALLY LINK THE NODES TO CREATE THE DESIRED TREE STRUCTURE.
# INITIALIZE THE NODE WITH A VALUE AND SET LEFT AND RIGHT CHILDREN TO NONE

class Node: #THIS IS THE BASE OF THE NODE LIKE A BLUEPRINT FOR CREATING NODES IN THE BINARY TREE, EACH NODE WILL HAVE A VALUE AND TWO POINTERS (LEFT AND RIGHT) THAT CAN POINT TO OTHER NODES OR BE NONE IF THERE ARE NO CHILDREN, THIS STRUCTURE ALLOWS US TO BUILD COMPLEX TREES BY LINKING NODES TOGETHER THROUGH THESE POINTERS
    def __init__(self, value): #THIS SERVES AS AN EMPTY SHIELD TO PROTECT THE NODE FROM BEING CREATED WITHOUT A VALUE, BECAUSE IN A BINARY TREE, EACH NODE SHOULD HAVE A VALUE, AND THE LEFT AND RIGHT CHILDREN CAN BE NONE IF THEY DON'T EXIST, BUT THE VALUE SHOULD ALWAYS BE PRESENT, THIS IS A DESIGN CHOICE TO ENSURE THAT OUR TREE NODES ARE ALWAYS VALID AND CONTAIN MEANINGFUL DATA
        self.value = value # ASSIGN THE VALUE TO THE NODE, THIS CAN BE ANY DATA TYPE (NUMBER, STRING, OBJECT, ETC.) THAT WE WANT TO STORE IN THE TREE
        self.left = None # SET THE LEFT CHILD TO NONE INITIALLY
        self.right = None # SET THE RIGHT CHILD TO NONE INITIALLY


class BinaryTree: # DEFINE A CLASS FOR THE BINARY TREE ITSELF
    def __init__(self): # INITIALIZE THE BINARY TREE WITH ROOT SET TO NONE, THIS IS LIKE AN INVERTED TREE STRUCTURE WHERE THE ROOT IS THE TOP NODE AND THE CHILDREN ARE BELOW IT, THIS IS A COMMON WAY TO REPRESENT TREES IN PROGRAMMING, AND IT ALLOWS US TO EASILY TRAVERSE THE TREE STARTING FROM THE ROOT AND MOVING DOWN TO THE CHILDREN
        self.root = None # SET THE ROOT OF THE TREE TO NONE INITIALLY

    # METHOD TO PRINT THE ENTIRE TREE STRUCTURE USING RECURSIVE IN-ORDER TRAVERSAL
    def print_tree(self): #THIS METHOD SERVES AS A PUBLIC INTERFACE TO PRINT THE TREE, IT CALLS A HELPER METHOD THAT DOES THE ACTUAL WORK OF TRAVERSING AND PRINTING THE TREE, THIS IS A COMMON DESIGN PATTERN IN OBJECT-ORIENTED PROGRAMMING WHERE WE HAVE A PUBLIC METHOD THAT CALLS A PRIVATE HELPER METHOD TO PERFORM THE RECURSIVE LOGIC, THIS KEEPS THE PUBLIC INTERFACE CLEAN AND EASY TO USE, WHILE THE HELPER METHOD CAN FOCUS ON THE DETAILS OF HOW TO TRAVERSE AND PRINT THE TREE
        self._print_tree_helper(self.root) # CALL THE HELPER METHOD STARTING FROM THE ROOT

    # HELPER METHOD FOR PRINTING THE TREE RECURSIVELY
    def _print_tree_helper(self, node):
        # CHECK IF THE CURRENT NODE IS NOT NONE
        if node is not None: # IMPORTANT: BASE CASE >> CHECK IF THE CURRENT NODE IS NOT NONE, THIS IS CRUCIAL TO AVOID INFINITE RECURSION AND TO KNOW WHEN TO STOP TRAVERSING THE TREE, IF THE NODE IS NONE, IT MEANS WE HAVE REACHED A LEAF NODE'S CHILDREN, AND WE SHOULD NOT CONTINUE TRAVERSING IN THAT DIRECTION
            self._print_tree_helper(node.left) # RECURSIVELY PRINT THE LEFT SUBTREE, THIS WILL GO ALL THE WAY DOWN TO THE LEFTMOST NODE BEFORE PRINTING ANY VALUES, THIS IS BECAUSE IN AN IN-ORDER TRAVERSAL, WE VISIT THE LEFT CHILDREN FIRST, THEN THE CURRENT NODE, AND THEN THE RIGHT CHILDREN
            print(node.value) # PRINT THE VALUE OF THE CURRENT NODE, THIS HAPPENS AFTER WE HAVE TRAVERSED THE LEFT SUBTREE, SO THE VALUES WILL BE PRINTED IN IN-ORDER SEQUENCE (LEFT, ROOT, RIGHT)
            self._print_tree_helper(node.right) # RECURSIVELY PRINT THE RIGHT SUBTREE, THIS WILL HAPPEN AFTER WE HAVE PRINTED THE CURRENT NODE, SO THE RIGHT CHILDREN WILL BE PRINTED LAST IN THE IN-ORDER SEQUENCE

# EXAMPLE USAGE TO BUILD A SIMPLE TREE MANUALLY
# CREATE A BINARY TREE INSTANCE
tree = BinaryTree()
# CREATE THE ROOT NODE WITH VALUE 1
tree.root = Node(1) # CREATE THE ROOT NODE WITH VALUE 1
tree.root.left = Node(2) # CREATE AND ASSIGN LEFT CHILD OF ROOT WITH VALUE 2
tree.root.right = Node(3) # CREATE AND ASSIGN RIGHT CHILD OF ROOT WITH VALUE 3

# WE FINALLY CALL THE PRINT METHOD TO DISPLAY THE TREE
tree.print_tree()

"""THE BINARY TREE STRUCTURE WILL ALWAYS FOLLOW AN EXACT ORDER, FIRST WE GO ALL THE WAY TO THE LEFTMOST NODE, 
THEN WE PRINT THE VALUE OF THE CURRENT NODE (ROOT/GRANDPA), AND THEN WE GO TO THE RIGHT CHILDREN, THIS IS CALLED IN-ORDER TRAVERSAL, 
AND IT GUARANTEES THAT THE VALUES ARE PRINTED IN A SPECIFIC SEQUENCE BASED ON THE STRUCTURE OF THE TREE, IN THIS EXAMPLE, 
THE LEFT CHILD (2) WILL BE PRINTED FIRST, THEN THE ROOT (1), AND THEN THE RIGHT CHILD (3), SO, IN SUMMARY...
THE ORDER OF THE PRINTED VALUES WILL BE:
2   ← LEFT CHILD OF ROOT
1   ← ROOT NODE
3   ← RIGHT CHILD OF ROOT"""

"""ANALOGY: FAMILY TREE, WHERE THE ROOT IS THE GRANDPARENT, THE LEFT CHILD IS ONE PARENT, AND THE RIGHT CHILD IS ANOTHER PARENT"""
"""ANALOGY: A TREE IN NATURE, WHERE THE ROOT IS THE BASE OF THE TREE, THE LEFT CHILDREN ARE ONE BRANCH, AND THE RIGHT CHILDREN ARE ANOTHER BRANCH"""